# spring
spring:
  application:
    name: handwrite-recognition-service

  # MongoDB
  data:
    mongodb:
      uri: ${MONGO_URI}
      host: ${MONGODB_HOST}
      port: ${MONGODB_PORT}
      username: ${MONGODB_USERNAME}
      password: ${MONGODB_PASSWORD}
      database: handwrite-mongodb
      authentication-database: admin

  # RabbitMQ
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

  # Spring Cloud
  cloud:
    # Eureka
    client:
      hostname: handwrite-recognition-service
    # Config
    config:
      uri: ${CONFIG_SERVER_URI}
      username: ${CONFIG_SERVER_USERNAME}
      password: ${CONFIG_SERVER_PASSWORD}
      name: spring
      profile: dev
      label: main
    # Bus
    bus:
      enabled: true


server:
  port: 8080
  servlet:
    context-path: /api/v1/handwrite

# Eureka 통신
eureka:
  instance:
    prefer-ip-address: false
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${DEFAULT_EUREKA_URL}

# Logging
logging:
  level:
    org:
      springframework:
        web: DEBUG